apiVersion: v1
kind: Service
metadata:
    name: svc-graph
    namespace: verdict
spec:
    ports:
        -
            port: 8050
            targetPort: 8050
            protocol: TCP
            name: http
    selector:
        aspect: graph