apiVersion: v1
kind: Service
metadata:
    name: svc-genes
    namespace: verdict
spec:
    ports:
        -
            port: 8080
            targetPort: 8080
            protocol: TCP
            name: http
    selector:
        aspect: genes