apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        name: genes-deployment
    name: genes-deployment
    namespace: verdict
spec:
    replicas: 1
    selector:
      matchLabels:
        aspect: genes
    template:
        metadata:
          labels:
            aspect: genes
        spec:
            containers:
                -
                    name: genes
                    image: 'browninc.azurecr.io/verdict-genes:latest'
                    ports:
                        - containerPort: 8080
                          protocol: TCP
                    env:
                        - name: DB_URI
                          value: "bolt://svc-db.verdict:7687"
                        - name: PORT
                          value: "8080"
                        - name: HTTP_ROOT
                          value: "/__/gene"
                        - name: DB_USER
                          value: "neo4j"
                        - name: DB_PASSWORD
                          value: "neo4j"