apiVersion: v1
kind: Service
metadata:
    name: svc-db
    namespace: verdict
spec:
    type: ClusterIP
    ports:
        -
            port: 7687
            targetPort: 7687
            protocol: TCP
            name: bolt
        -
            port: 7474
            targetPort: 7474
            protocol: TCP
            name: browser
    selector:
        aspect: db