apiVersion: v1
kind: Service
metadata:
    name: svc-diseases
    namespace: verdict
spec:
    ports:
        -
            port: 8010
            targetPort: 8010
            protocol: TCP
            name: http
    selector:
        aspect: diseases

