apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: db-deployment
    namespace: verdict
spec:
    selector:
      matchLabels:
        aspect: db
    replicas: 1
    template:
        metadata:
          name: neo4j
          labels:
            aspect: db
        spec:
            volumes:
            - name: verdict-neo4j-data
              azureFile:
                shareName: neo4j
                readOnly: true
                secretName: verdictneo4j-storage-secrets
            containers:
                -
                    resources: {}
                    name: db
                    image: "neo4j:3.5.6-enterprise"
                    imagePullPolicy: IfNotPresent
                    readinessProbe:
                      periodSeconds: 5
                      initialDelaySeconds: 50
                      httpGet:
                        path: /
                        scheme: HTTP
                        port: 7474
                    command:
                      - "/bin/bash"
                      - "-c"
                      - |
                        exec /docker-entrypoint.sh /var/lib/neo4j/import/do-import.sh 
                    env:
                      - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
                        value: "yes"
                        #cypher.forbid_shortestpath_common_nodes
                      - name: NEO4J_cypher_forbid__shortestpath__common__nodes
                        value: "false"
                      - name: NEO4J_dbms_security_auth__enabled
                        value: "false"
                      - name: NEO4J_dbms_jvm_additional
                        value: "-Xss10M"
                      - name: NEO4J_dbms_memory_heap_initial__size
                        value: "2G"
                      - name: NEO4J_dbms_memory_heap_max__size
                        value: "5G"
                    volumeMounts:
                        - mountPath: /var/lib/neo4j/import
                          name: verdict-neo4j-data
                    ports:
                      - containerPort: 7474
                        name: browser
                      - containerPort: 7687
                        name: bolt
---
apiVersion: v1
kind: Secret
metadata:
    labels:
        name: verdictneo4j-storage-secrets
    name: verdictneo4j-storage-secrets
    namespace: verdict
data:
  azurestorageaccountkey: S3VUeXpUVWRad1lISTVjYXRtbHRBa2RWaDZQN0ZOdElrMVRuZEtDTlpVZmh2ZkpTbm5VUGtYQkRqZWhmNHV5MkJCNTFsYjFoczZtdFJGc2VQT3FmMHc9PQ==
  azurestorageaccountname: dmVyZGljdG5lbzRq